//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeritageEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book : Item
    {
        public int ISBN { get; set; }
        public long Page { get; set; }
    }
}
